apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grade-submission-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/babsontimie/kubernetes-cicd-tutorial.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


# kubectl create secret docker-registry ghcr-secret --docker-server=ghcr.io --docker-username=<babsontimie> --docker-password=<Coderepo-password> --namespace=default	
